### PR TITLE
Fix MD link, intended to show link instead of image

### LINKED ISSUE #2: Broken link on readme.
image

### PR DESCRIPTION
**Pull request by jovylle**
fixes #2 2

### CODE REVIEW

**Comment by roytang** [comment]
Huh, surprising, but ok. Thanks!

**Comment by roytang** [comment]
Oops, just realized this merge will be overwritten the next time the file is auto-generated. Thanks still, maybe you needed it for Hacktoberfest or something?

**Comment by jovylle** [comment]
I procrastinate a lot, but I choose to procrastinate related to my work. Yes related to hacktoberfest but my goal is just building habit of contributing so its fine if this particular fix is not included on hacktoberfest.

**Comment by jovylle** [comment]
I wonder what tool you use to automate edit of this readme file.

**Comment by roytang** [comment]
It's a python script in my blogging software

**Comment by jovylle** [comment]
Oh, Thank you. got it, and its calling some github apis with API keys to make it authorized, right

**Pull request merged**
